### ISSUE TITLE
Dont build on opensuse 12.1

### ISSUE THREAD

**Issue by fpersson** [fpersson/startrail#5]
/usr/lib/gcc/i586-suse-linux/4.6/../../../../i586-suse-linux/bin/ld: CMakeFiles/startrail.dir/main.cpp.o: undefined reference to symbol 'boost::system::system_category()'
/usr/lib/gcc/i586-suse-linux/4.6/../../../../i586-suse-linux/bin/ld: note: 'boost::system::system_category()' is defined in DSO /usr/lib/libboost_system.so.1.46.1 so try adding it to the linker command line
/usr/lib/libboost_system.so.1.46.1: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
make[2]: **\* [bin/startrail] Fel 1
make[2]: Lämnar katalogen "/home/fredrik/startrail"
make[1]: **\* [bin/CMakeFiles/startrail.dir/all] Fel 2
make[1]: Lämnar katalogen "/home/fredrik/startrail"
make: **\* [all] Fel 2
make: Lämnar katalogen "/home/fredrik/startrail/bin"

**Comment by fpersson** [comment]
Troligen fixat.
